version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
      - no-changelog
    commit-message:
      prefix: "deps(go)"
    groups:
      go-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript
      - no-changelog
    commit-message:
      prefix: "deps(web)"
    groups:
      web-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
      - no-changelog
    commit-message:
      prefix: "deps(ci)"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - docker
      - no-changelog
    commit-message:
      prefix: "deps(docker)"
