all:
  children:
    main:
      hosts:
        main_server:
          ansible_host: 184.34.95.138
          ansible_user: ubuntu
    probes:
      hosts:
        probe_us_east_1:
          ansible_host: 34.224.157.236
          ansible_user: ubuntu
          probe_node_name: us-east-1
          probe_region: us-east-1
        probe_ap_northeast_1:
          ansible_host: 13.193.138.246
          ansible_user: ubuntu
          probe_node_name: ap-northeast-1
          probe_region: ap-northeast-1
        probe_ap_southeast_1:
          ansible_host: 52.74.247.196
          ansible_user: ubuntu
          probe_node_name: ap-southeast-1
          probe_region: ap-southeast-1
        probe_eu_central_1:
          ansible_host: 35.157.229.223
          ansible_user: ubuntu
          probe_node_name: eu-central-1
          probe_region: eu-central-1
