---
- name: common setup (all hosts)
  hosts: all
  become: true
  roles:
    - common

- name: main server
  hosts: main
  become: true
  roles:
    - main-server

- name: probe nodes
  hosts: probes
  become: true
  roles:
    - probe
